DROP TABLE IF EXISTS `tester`;
CREATE TABLE IF NOT EXISTS `tester` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `email` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `gender` int(8) NOT NULL DEFAULT '1',
  `age_grp` int(8) NOT NULL DEFAULT '0',
  `test_date` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `question`;
CREATE TABLE `question` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `question_text` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `cat_id` int(8) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `question` (`question_text`, `cat_id`) VALUES 
('Surprises make you tick.', 14),
('You often question situations of the past.', 7),
('You gladly accept defying opinions.', 11),
('You''d rather spend time with familiar faces instead of people you don''t know.', 8),
('You believe that life is a learning experience where failing is allowed.', 1),
('You are the leader who keeps your team focused on their goals.', 20),
('You enjoy exploring outside your comfort zone.', 2),
('Rather than observing others, you prefer experiencing things for yourself.', 16),
('Seeking opportunities to be challenged is something you usually do.', 3),
('You like to focus your efforts on maximizing a single attribute.', 15),
('You appreciate the learning process more than the final product.', 12),
('You think of your future instead of dwelling in the past.', 7),
('Getting to know new people is a thrilling and enjoyable experience.', 5),
('You can calmly assess potential losses and gains.', 1),
('You have the capacity to naturally analyse situations and confidently present sound decisions.', 9),
('You dismiss the symptoms to search for the cause.', 4),
('You rejoice after conquering a goal.', 10),
('You are open-minded when observing the world around you.', 19),
('You are qualified to lead people.', 11),
('You love solving complex problems.', 4),
('Your decisions are aligned with your core values.', 17),
('You feel like dreaming is only worth it if you take action.', 16),
('Everything in this world is uncertain.', 1),
('You have a certain degree of confidence in every decision you make.', 6),
('You do your best to achieve the best possible outcome.', 2),
('You figure out what needs to be done and you''re quick to act on it.', 9),
('Taking action is more important than planning.', 16),
('You deeply feel like executing on ideas.', 13),
('You fancy networking and connecting with people.', 5),
('You uphold and share your beliefs with others.', 11),
('You like to compliment others for their achievements.', 10),
('Studying is never too much as long as you learn.', 12),
('You feel excellent dealing with different and unknown situations.', 2),
('You feel attracted to the high-achievers in life.', 15),
('You love living in the present moment.', 21),
('You love finding solutions for external problems.', 4),
('You feel like having general knowledge is better than having specific knowledge.', 15),
('You feel comfortable working in a team.', 8),
('You are keen on turning away unexpected requests.', 21),
('Others turn to you for motivation.', 7),
('You enjoy uncovering complex knowledge others don''t have.', 19),
('Personal attributes captivate you, and you seek to improve them.', 15),
('The possibilities that lie in the future are often a reason for you to feel excited.', 7),
('Success is not just money, fame, and relationships.', 17),
('You like to persuade others into accepting what you have to say.', 5),
('You are a perfectionist and expect others to live up to the same standard.', 14),
('You are brave and take responsibility to whatever you commit yourself to.', 18),
('You are passionate about your work and you want it to be significant.', 17),
('You feel a relationship is only truly valuable if it is genuine.', 8),
('You are known as a reliable human being.', 18),
('Working without a clear path to follow is meaningless.', 20),
('You make your point across through storytelling.', 13),
('You are determined in overcoming resistance and confusion.', 9),
('You have a hard time working more than 8 hours.', 3),
('You''re an adept of keeping yourself organized by creating a to-do list.', 14),
('You like to find the most impactful words of every situation.', 13),
('Are willing to hurt yourself by getting close to others.', 8),
('After accomplishing your goals, you are out to find more goals to pursue.', 3),
('Coming up with excuses to justify your failures is intolerable.', 18),
('You are mentally strong to achieve your goals regardless of any obstacles.', 3),
('You like to make your own decision without the help of others.', 6),
('You like to manage what is outside your scope.', 2),
('You feel lost if others don''t give you a clear and steady path to follow.', 20),
('You are excited to start every time a new project pops up.', 16),
('The most exciting phase is when you are a complete beginner and have to climb your way up to expert.', 12),
('You regularly question everything you do and every decision you make.', 4),
('Hate is something people learn; they are not born with it.', 5),
('You dismiss everything keeping you from reaching your goals.', 20),
('You don''t dwell too long on old problems and quickly move on to bigger and better things.', 21),
('You feel like a person is measured by her commitment to stick to her promises.', 18),
('Growth captivates you, not because you aspire to be the best.', 12),
('You communicate better through describing, explaining, speaking or writing.', 13),
('You feel like the future is built like a puzzle, one piece at a time.', 21),
('Your actions exude assurance and a deep sense of confidence.', 6),
('Ethics and responsibility play a big role in every action you take.', 17),
('You always seek to have a positive outlook on life.', 10),
('Certain thoughts and ideas can rally and motivate you.', 19),
('You smile even without a reason to - you are a happy-go person.', 10),
('You feel awesome for trying out new stuff (no, not drugs).', 1),
('You have an urge to be in control of what you don''t have any control over.', 14),
('You inspire people to be true to themselves.', 11),
('You can usually find the best solution amidst an ocean of confusion.', 9),
('You feel pumped every time an idea arises in your brain.', 19),
('You trust and take pride in your personal strengths.', 6);

DROP TABLE IF EXISTS `value`;
CREATE TABLE IF NOT EXISTS `value` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `value_text` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `value_val` int(8) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

INSERT INTO `value` (`id`, `value_text`, `value_val`) VALUES
(1, 'Disagree Strongly', 0),
(2, 'Disagree', 30),
(3, 'Undecided', 50),
(4, 'Agree', 70),
(5, 'Agree Strongly', 100);

DROP TABLE IF EXISTS `answer`;
CREATE TABLE IF NOT EXISTS `answer` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `tester_id` int(8) NOT NULL DEFAULT '0',
  `question_id` int(8) NOT NULL DEFAULT '0',
  `value_id` int(8) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `category`;
CREATE TABLE IF NOT EXISTS `category` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `cat_name` varchar(32) NOT NULL DEFAULT '',
  `cat_description` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=22 DEFAULT CHARSET=utf8;

INSERT INTO `category` (`id`, `cat_name`, `cat_description`) VALUES
(1, 'Risk Taking', 'The Risk Taker is someone who relies on their intuition when it comes to making decisions. The consequences may be dire, but they’re willing to risk it all in pursuit of what they want.\r\n•         Your own abilities are a crucial part of risk taking, and you should learn to recognize what unique abilities you have that will let you pursue risks.\r\n\r\n•         If you think a risk is uncomfortable (though not dangerous) do not just dismiss it. See if there is a way to overcome the consequences. \r\n\r\n•         Watch out for available opportunities and be prepared to take them. They may not work out, but you’ll grow from the experience. And will make better decisions in the future.   \r\n\r\n•         Don’t focus on the consequence, outcomes, or results. Try something new every day. \r\n\r\n•         Everyone feels fear, it’s a natural response to many things. Always be prepared to overcome it.'),
(2, 'Resourcefulness', 'Resourceful individuals are able to operate in any environment. When things are busy, they’re able to take stock of what’s around them and use what they have to their best advantage. \r\n•	Responsibility is the opportunity to work up how resourceful you can be, so be prepared to take it on whenever you can.\r\n\r\n•	You will do best at a higher position, such as a manager, so that you will have access to more resources.\r\n\r\n•	Take command when you can, figuring out how to use other people’s strengths in a team environment is part of being resourceful.\r\n\r\n•	You will learn to thrive in times where chaos is abundant. It’s where you learn to use what you have on hand. \r\n\r\n•	There is rarely one way to complete a task. Look for other ways to solve problems.\r\n\r\n•	If you believe someone is a bad influence, whether at work or in your personal life, avoid them. Being around them will only force you to focus on dealing with them.'),
(3, 'Purpose', 'While many people are content to be slackers, a purposeful man or woman is the opposite. They love to work, provided that they’re following their passion. \r\n•	Don’t let yourself get bored. Keep a book about what you’re passionate about with you, or bring a notebook and brainstorm how you can further your goals.\r\n\r\n•	Avoid meetings where you won’t be required. When you do attend them, be as engaged and active as possible.\r\n\r\n•	Never let yourself get rusty. Keep tabs on where you are, how far you’ve come, and where you’re going.\r\n\r\n•	No matter how much purpose you have, you must avoid slackers. They will only slow you down and throw you off track.\r\n\r\n•	If you spend too much time at rest, or on things that do not challenge you, you will find that your motivation will fade away. \r\n\r\n•	Accept praise for something you have achieved, but do not bask in it. Prepare a new goal soon after.\r\n\r\n•	If you are offered a promotion, do not accept it blindly. Straying away from what you love may not be the best idea for you.'),
(4, 'Problem Solving', 'Some people freeze up when they don’t have a solution to a problem. Others jump into action and try to figure out the best possible answer, even if that means missing a deadline or two.\r\n•	Problem solving is not always an innate skill. Many times you need prior knowledge of a subject in order to solve it. Read up on the problems in your field, as well as the concept of problem solving. \r\n\r\n•	If you need to make a decision or craft a solution, you will often need as much detail as possible. Ensure that you are not putting off solving the problem or procrastinating. This will only cause more trouble in the future.\r\n\r\n•	Life can often be difficult, make sure to tell others you appreciate when they say you have done a good job. Make sure to return the favor as well, this will only help you in regards to friendships and networking.\r\n\r\n•	People are easily led astray by flowery words and incorrect assumptions. Pay attention to the truth of the world, hard data, logic, and numbers, and you will go far.\r\n\r\n•	While you focus on the hard truths of the world, do not allow others to use fluff as ‘evidence’ to support their viewpoints. You may not be led astray, but others will be. Keep everyone honest. \r\n\r\n•	If you happen to come across information that gives you a better grasp of a situation, do not hide it from others. Share it with everyone you can. People will remember the kindness.\r\n\r\n•	Deadlines can seem like they come out of nowhere, especially when you’re focused only on solving the problem. If you become focused on doing something right more than on time, you may miss a deadline.'),
(5, 'Salesmanship', 'Salesmanship doesn’t always mean selling products to people. Sometimes it’s about convincing a friend not to make a bad decision, a boss about a raise, or a community about a cause.\r\n•	Strangers are not to be feared. Do your best to meet new people whenever you can. They may become an important person in your life, or they may simply make you feel better about your day. \r\n\r\n•	Don’t wait for others to step up. Become the ‘person to speak to’ for the groups, communities, and organizations that you are part of. You will make the lives of others easier, and perhaps learn a few new things as well. \r\n\r\n•	Who does not love to be remembered? Develop and refine a system to learn and remember everyone’s name and face.\r\n\r\n•	Not every relationship has to become the deepest level of friendship. If it makes sense, simply meet, have fun, and move on. There is no shame in having a light friendship, as long as you have many.\r\n\r\n•	In your pursuit of preparing the winning proposal, make sure that you are not messing with the visions of other people. People do not like their dreams or values walked over, even if done with good intentions. \r\n\r\n•	Be proactive and build a good reputation for your community, your team, and your favorite organizations (such as nonprofits).'),
(6, 'Self Motivation', 'Who needs their hand held? Not someone who is self-motivated. There’s no need to tell someone who is self-motivated what to do, just give them the objective. Sometimes though, the result is a bit…unexpected.\r\n\r\n•	Do not wait for someone to show you the exact steps. Make decisions yourself and take the lead when you can.\r\n\r\n•	No success can be found without a bit of determination and stick-to-it-ness. Take on jobs where you have to be persistent.\r\n\r\n•	It can be impossible to stay motivated if you are constantly changing directions. Accept roles that asks you to be stable and rock-solid.\r\n\r\n•	Try to ensure the development of a strong identity and that you create the change in the world.\r\n\r\n•	If you wish to find success in your life and make the world a better place, you MUST accept the fact that you control your own world. Make sure others understand this as well. \r\n\r\n•	Do not shy away from criticisms. In order to operate as efficiently as possible you will need to review your failures as well as your successes. There are lessons to be found in each.'),
(7, 'Visionary', 'There are some in this world who are not content to accept how things are. They have visions of how things should be, and can often rally others and inspire them with this dream. Found in politics, nonprofits, and every community, visionaries do their best to make the world a better place.\r\n•	Your vision of the future should not be kept within your own mind. Share it with the world, tell your friends, families, and community about all you imagine. \r\n\r\n•	In the workplace, speak up more often about your views on the company direction, recent projects, or how a meeting went. \r\n\r\n•	Make a point to sit down and read articles that cover the future of all things. This will help refine your vision and make it a reality.  \r\n\r\n•	Planning committees deal almost exclusively with the future. Sitting on the committee will give you an opportunity to make your visions a reality. \r\n\r\n•	Some roles are more vision-oriented than others. If you can, step into those that will force you to use your dreams of the future as a basis for development of new ideas. \r\n\r\n•	Many people can never even imagine what the future will be like. Sit down and talk with them so that they can learn to grow beyond the present moment.'),
(8, 'Teamwork', 'Group projects are not an opportunity to slack off, they’re a chance to reach higher than ever before. Teamwork individuals are fond of working with others as it allows them to achieve success that is far beyond the limits of what a single person can do. \r\n•	Close friendships are something to be cherished. Keep your relationships with others in mind when making decisions, or you may come to regret it. Organize your life around your close relationships and keep them in planning exercises.\r\n\r\n•	Roots tend to grow deep. Do not uproot your life and move too often. Instead, enjoy the deep bonds you will naturally develop with people. \r\n\r\n•	A team works best when the team members know each other and respect each other. Learn all you can about your team and bond with them whenever you can.  You will find greater success doing this. \r\n\r\n•	Teamwork means people will naturally come to you. Attempt to be a loyal friend, never betray someone’s trust, and always abhor betrayal.  \r\n\r\n•	There is little better, or more rewarding, in this world than a genuine relationship with someone. Nurture them, and you will go far.  \r\n\r\n•	Teamwork means being selfless and generous. By accepting that not everything can be about you, you will be noticed and rewarded for it.'),
(9, 'Strategic Thinking', 'Those with Strategic Thinking skills do their best work when viewing the problem from a high-level perspective. They don’t get bogged down in the minutiae or minor details, instead focus on the big picture.\r\n•	Take the lead when your organization is preparing a strategy. This experience will be invaluable for you, and you will remember it fondly.\r\n\r\n•	High level planning and risk management occur often, find a way to become involved in these processes.\r\n \r\n•	It’s almost impossible to develop a reliable strategy at a moment’s notice. When you are tasked with creating a strategy, always make sure you have given yourself plenty of time to consider it.\r\n\r\n•	Strategy has been studied by hundreds of experts over thousands of years. Attend a University class, read books, or learn the history to grow your skill.  \r\n\r\n•	There are countless opportunities around you to share what you think, whether it be via reports, presentations, or videos. Find them and utilize them.\r\n\r\n•	Not everything has to be brand new. Find a solution that has worked somewhere completely unrelated to your current position, and you may find a solution to your current problem.'),
(10, 'Optimism', 'Always look on the bright side of life. That’s the optimist’s motto. There’s a silver lining in every situation, even if no one else sees it (or wants to hear it).\r\n•	When you are close to customers, make a point to be bright and cheery. You may turn someone’s day around (and you’ll likely become happier for it). \r\n\r\n•	Events are the bastion of optimism. Offer to help plan events, even small things like a party, and you’ll find yourself bringing cheer to the world. \r\n\r\n•	No matter who you are, a quick joke and a solid attitude will make almost anyone in the world your friend.\r\n\r\n•	Just because you are being optimistic does not mean you have to be in a great mood. In fact, you can often let people know that “I’m having a bad day today,” and they will understand. Looking on the bright side does not mean that you must always be chipper. \r\n\r\n•	Stay away from those who have developed a cynical outlook on life.  It will sap your energy, and attempting to cheer them up will never go well. \r\n\r\n•	Whenever you achieve something, find a way to celebrate. It does not have to be large or with too many people, but a few good friends and a nice dinner will help ensure a strong optimistic outlook.'),
(11, 'Leadership', 'For the leaders, it is not always about getting a job done. More often, it’s about making sure everyone under your watch gets what they need and that no one struggles. Leaders are always found with their team, and never managing from a long distance. \r\n\r\n•	Projects often stall without a leader. Step in when you can and get them moving again! You may be the project’s only hope for reaching the deadline (or finishing at all). \r\n\r\n•	Never be afraid to give an honest opinion. In a world where everyone is afraid of offending people, your honesty can help set friends, companies, and communities straight.  \r\n\r\n•	If you feel that being supervised affects your performance, speak up about it. Most managers would prefer a productive employee that they do not need to watch. \r\n\r\n•	As you take the lead, you may find that you are brushing coworkers the wrong way, missing your own deadlines, and more. Be mindful of these things and avoid them. \r\n\r\n•	When you take the lead, your style may be that of a strong, dominant commander. This is not a problem, but let those under you know that you are not being personal. You simply want the best for everyone.  \r\n\r\n•	It is not a waste of time to sit down and discuss with others who you are. Often, we’d rather understand someone than try to change them to fit our liking.'),
(12, 'Curiosity', '“Curiosity killed the cat, but satisfaction brought it back,” is the motto of the curious. They don’t just love to hear secrets; they love to unravel the mysteries of the universe. Few others take such joy in discovering the wonders of the world and expanding their knowledge. \r\n•	Fast moving fields are perfect industries for the curious. Constantly learning new things will make you happier than ever.  \r\n\r\n•	Do not be content with where you currently get your information from. There is always someone wiser as a mentor, a more comprehensive guide, or a greater library. \r\n\r\n•	Have some fun with things. Track the progress of how much you have learned along the way, and make sure to celebrate when you break a mental block.\r\n\r\n•	The world is too full of jack-of-all-trades. Become an expert or thought leader in your field. You will be sought out by many people for your advice. \r\n\r\n•	Do not attempt to entirely motivate yourself. Find a friend or coworker who enjoys pushing you to grow what you know.\r\n\r\n•	The greatest way to learn is by teaching. Whether formal or informal, find a way to share all of the things you know. Not only will you be learning, but will help spread knowledge across your community. \r\n\r\n•	Education is rarely free. Make a point to set aside a bit of your income so that you can attend classes, buy books, and continue your education.'),
(13, 'Communication', 'There is little that cannot be sold with a bit of honest communication. Heart to hearts, soul baring’s, and mediation of disgruntled parties are all places you’ll find someone with strong communication skills. \r\n\r\n•	Communication is a skill that can be learned and improved. Find some time in your day to take courses or read books. There is so much more for you to know about communication.  \r\n\r\n•	Attend speaking events, comedy shows, or rallies where people will be entertained. You will learn how to keep people enraptured with your words. \r\n\r\n•	Storytelling is a time honored way of communicating, stretching back to caveman times. Make a point to understand your culture and that of where you live. People will love to hear what you know. \r\n\r\n•	Your life and culture is not the only one. Why not sit down and hear the stories and experiences of others? We often gain more by listening than speaking.\r\n\r\n•	Social events are a key part in how we communicate with one another, so make sure you are participating in many of them. If you do not have the opportunity, set up a few yourself. \r\n\r\n\r\n•	Many people struggle with the most basic communication. Offer to help them out and create something a bit more interesting and thought out. \r\n\r\n•	Do not be afraid to take public speaking classes. When you are ready, move on to the more advanced stuff.'),
(14, 'Balance', 'Balanced individuals put all of their energy into turning the most chaotic events into nice and ordered processes. There is no mess too great for them, for they love nothing more than rolling up their sleeves and cleaning up.  \r\n•	Groups are always struggling with chaos, often caused by infighting and disagreements. Sit down with them and resolve the chaos that they have caused. The order will make them more productive.  \r\n\r\n•	A physical mess will naturally force you off balance and give way to chaos. Keep a clean room to keep a clean mind.\r\n•	An unexpected deadline will throw off your entire plan. Things will fall into chaos. Make sure you have advance notices for anything involving a deadline or mandatory participation. \r\n\r\n•	Let others know that surprises can distract you and are very likely to bother you. As long as you tell them before they have planned your surprise party, they are likely to understand. \r\n\r\n•	Do not attempt to resolve everything in the moment. Take a bit of time to sit down and consider what your goals are, and then develop plans to meet them.\r\n\r\n•	Others are likely struggling more than you ever have in regards to managing their time and productivity. You can provide a bit of guidance and pointers.  \r\n\r\n•	The unknown will only cause chaos and confusion. Prepare for the unexpected and do all you can to make sure a sudden disturbance will not mess with your work.'),
(15, 'Ambition', 'Never content, the ambitious are always on the lookout for ways to grow, both professionally and personally. Whether it’s launching a new business, climbing the corporate ladder, or furthering their cause, the ambitious are always hard at work. \r\n•	The things that do not work cannot be fixed. Throw them out. Focus your attention on making the things that work, work even better.\r\n\r\n•	If you enter into a role that asks you to constantly solve problems, then you will not have time to grow and seize new opportunities. Be mindful of this. \r\n\r\n•	There is no good to be gained from focusing so much on your weaknesses, no matter what they are. Focus on your strengths and how to maximize them.\r\n\r\n•	If you wish to climb high, then you need to make sure you are using your strengths as much as possible. Even if you have to give up money for it, you will end up in a better position by using your unique talents.\r\n\r\n•	In every organization there are systems and values that should be brought to the forefront and expanded. When you can, build a team to find them and give them strength. Your boss will thank you for it.\r\n\r\n•	“What gets measured gets managed.” Implement, or join in, a program that measures you and your fellow employee’s productivity. You will find areas to improve on, as well as individual strengths you can rely on.'),
(16, 'Determination', 'The determined man or woman is unstoppable. It does not matter the difficulties that lay in front of them, they are willing to persevere at any costs. Sometimes, though, this starts to strain their relationships. \r\n•	There has never been the perfect system. Everything can be improved and expanded on, so always look for new improvements to make to your life or the systems you use.\r\n\r\n•	Make a point to start and organize a project, whether it be at work or just a neighborhood event. You will make yourself look good and give others an opportunity for fun or progress (both professional and personal). \r\n\r\n•	Use criticism, critiques, and feedback in order to adjust your approach and keep moving forward.\r\n•	Whenever you see a group that has become stuck, step in and help them out. You will be surprised what a bit of direction and persistence from you can accomplish for others.  \r\n\r\n•	Feeling a bit bummed out or unproductive today? Don’t sweat it, it happens to even the most determined people. Grab a pad and paper and think of some ways you can step up your game when tomorrow comes around. Get excited about these improvements. \r\n\r\n•	Be wary around people who want to endlessly analyze and overthink situations, but make no progress. They will slow you down, at best, or completely stall you at worse!'),
(17, 'Faith', 'For some people, their actions are a reflection of a Higher purpose. Those with faith are not always religious, but they always do their best to act in accordance with a strong internal set of values.\r\n•	You have a true passion that lies deep within you. Discover it and find a way to integrate it with your work, even if they appear to be unrelated. \r\n\r\n•	Great good can be achieved by aligning your values with that of others. Great evil can be achieved by the reverse, when you give up your values.\r\n\r\n•	If you find that you respect others for learning about your beliefs, give them the opportunity to do so. Do not be closed off out of fear or anxiety.\r\n\r\n•	There are things that are infinitely more important than money. But sometimes, many of us needed to be reminded of this fact. Do not forget it, and do not let others forget it.\r\n\r\n•	Just because people do not share your beliefs on a matter does not mean they do not respect them. Be willing to engage in discussions about how you feel.'),
(18, 'Integrity', 'A rare attribute in this day and age. Those with integrity are willing to stand by their values, sometimes to the detriment of their friendships or progress.\r\n•	Commitments are a key part of integrity. If you are constantly breaking them, people will think negatively about it. But if you consistently meet them, people will love you for it.  \r\n\r\n•	Avoid slackers or those with sketchy personalities whenever you can. No matter what, they will only hurt you. \r\n\r\n•	Never feel needed to hurry along and damage your end result. Quality over quantity at all times. If you must, take the time and explain this to others. \r\n\r\n•	Talk to your manager or boss and let them know that you would prefer to do things yourself. You do not need to be looked after, as that will only cause a problem.\r\n\r\n•	There is no greater way to strengthen or showcase integrity than by taking up a position that demands an ethical outlook. Seek these out and show the world the person you truly are. \r\n\r\n•	Integrity is a never-ending process. Sit down and ask yourself if there are new responsibilities you would like to add to your life. Be thoughtful and seriously consider them, and do not add them lightly. \r\n\r\n•	While you may ask yourself what new responsibilities you should take on, be mindful that you do not become overwhelmed. Ensure that you only accept what you feel you are capable of doing. Say no when you have to.\r\n•	You do not have to avoid being promoted to a supervisor position, but you should be careful about it. You may start to think you can do everything yourself, and this may offend the people beneath you. Trust them.'),
(19, 'Innovation', 'While others try to find time tested ways of solving problems, innovators prefer to use their resources to create an entirely new solution. Found in tech heavy fields, these individuals jump at the chance to create something that’s never been done before.\r\n•	Not all jobs will reward innovation, so find roles where you are encouraged to become an innovator. Many will even reward you financially for doing so. \r\n\r\n•	Common roles are designers of all types, sales strategists, growth marketing, or customer service representative. \r\n\r\n•	Do not try to innovate alone, you’ll just end up with a blank slate. Send out messages and bring others in on your project to help your brainstorming.\r\n\r\n•	It’s foolish to have a set time to innovate. Never stop thinking of ways that you could make the world better.\r\n\r\n•	If you find that words have a way of stimulating how you think about the world, embrace this. Pick up poems, fancy articles, or look up quotes to get your subconscious working. \r\n\r\n•	It’s impossible to make a decision without knowing how things work together. Do all you can to gather as much information as possible before you make a decision.\r\n\r\n•	Often we focus so much on making a choice that we fail to realize that there is an alternative option right under our nose. If you don’t like how something will turn out, make a point to look for another choice.'),
(20, 'Focus', 'A focused individual works best when they set a timeframe and have a concrete plan. They set their mind to something and achieve it, often letting lesser important stuff fall to the wayside.\r\n\r\n•	Don’t try to wing it. Sit down and set specific goals and deadlines for yourself so that you can focus on them. \r\n\r\n•	Whenever possible, try to control the work environment you are in. This way you can maximize your focus and not split your attention. \r\n\r\n•	Don’t just set a deadline and ignore it. Perform regular checkups on your progress to make sure you’re making headway.\r\n\r\n•	Sometimes, focusing too much may mean you ignore other people. Don’t be worried, just make an effort to make sure you are not hurting other people.\r\n\r\n•	Change can be a very difficult thing to deal with. See if there is a new goal you can set in accordance with changes.\r\n\r\n•	Looking to maximize your focus? Attend a time management seminar and find ways to add what you’ve learned to your life.\r\n\r\n•	Avoid meetings that do not have a clear outline or setup, they will only waste your time.'),
(21, 'Adaptability', 'Someone who is adaptable can make the best of any situation. When things don’t go as planned, those who are adaptable can spring into action and save the day. \r\n\r\n•	In order to succeed, you will need to find ways to prepare for the unfortunate and the unexpected. These things happen, and success means making the best of things. \r\n\r\n•	Do not go overboard on planning, especially if you find it boring. Instead, make sure that you have the resources available to adapt to new situations or resolve problems quickly if they were to arise.\r\n\r\n•	Feeling like you are not making much progress? Join up with a team who is on the move. The fast paced movement will keep you on your toes and give you plenty of opportunities to be adaptable. \r\n\r\n•	Pick up a number of small tasks, even if they are not easy, rather than something that is drawn out. These quick wins will invigorate you.\r\n\r\n•	By being adaptable you will have opportunities to provide knowledge and equipment to help other people succeed. Keep an eye out for these moments (and be prepared)!\r\n\r\n•	While setting goals is often a good move, do not look at “Target Goal Meetings” as anything but a waste of time. You will not find any decisions to be made there, instead, go out and make them yourself.');
